### ISSUE TITLE
Pulling JSON data on localhost source

### ISSUE THREAD

**Issue by mrtgradygft** [PavelLaptev/JSON-to-Figma#11]
Hi Pavel

I’ve been using your plugin for Figma on a project I’m working on (loving the new image replace function, by the way) but I’m running into a problem when trying to import the JSON via a URL.

It seems that I can’t import JSON from a localhost URL or local/protected range IP address because your plugin uses a Heroku proxy server to grab the JSON content, which obviously won’t tunnel in to a URL beginning with http://localhost, http://127.0.0.1 or http://192.168.x.x, etc.

Have I understood that correctly? Does the plugin require the JSON to be on a publicly accessible web server in order to be able to work? If not how do I get a local URL to deliver data to the plugin?

Thanks
Mark G

**Comment by PavelLaptev** [comment]
@mrtgradygft hi! Yes, I've added Heroku server to avoid CORS issues. But I'll solve this problem this weekend. Probably, will add a checker for this. For now, you can download the 2.5 version https://github.com/PavelLaptev/JSON-to-Figma/releases/tag/2.5 and use it.

I'll ping you here when I update the plugin.

Also, why you won't load a local file via "from local file" button?

**Comment by mrtgradygft** [comment]
Hi Pavel

We're able to load local file perfectly and that's great, but we're trying out a method for populating our Figma files from data held on a STRAPI headless CMS server internally on our network, hence using a local URL. 

Having a function that checks for internal/private URLs would be great. I hope you are able to add the feature, although I hope it doesn't take too much of your time so you can enjoy the weather this weekend.

Thanks,
Mark G

**Comment by PavelLaptev** [comment]
@mrtgradygft now I see the reason 😃 Sure, I'll add the checker, don't worry. Hope you can wait until Monday 😉 

Thanks for your feedback

**Comment by mrtgradygft** [comment]
👍

**Comment by PavelLaptev** [comment]
@mrtgradygft I added a check for "localhost" and "127.0.0.1". Could you test it? It should work now as the old version 2.5

**Comment by mrtgradygft** [comment]
Hi Pavel

It appears to be working perfectly.

Thanks very much for doing this, and doing it so fast!

Mark G

**Comment by PavelLaptev** [comment]
No problemo, @mrtgradygft 😉
