### ISSUE TITLE
Idea: Handling `null` types

### ISSUE THREAD

**Issue by tylermcrobert** [PavelLaptev/JSON-to-Figma#19]
Thank you so much for the plugin, it has radically increased my productivity. 

I did think of a small improvement. When items are currently null, the plugin throws an error. Instead, is there a way to hide the layer for the null values?

**Comment by PavelLaptev** [comment]
Hi, Tyler! Thank you for your donation 😉  I really appreciate this 🙏 It helps me to set my priorities. I wrote down your request and will implement it with the new release. Currently, I'm making a new Figma plugin, and right after it will refactor and update "JSON to Figma" plugin.
Thank you and have a great New Year!

**Comment by PavelLaptev** [comment]
@tylermcrobert fixed in the new version 4.0 🙂
