### ISSUE TITLE
Link local images

### ISSUE THREAD

**Issue by wolfgangbartelme** [PavelLaptev/JSON-to-Figma#66]
Hi,

is it possible to also link to local images… or does the plugin not have access to the local file system?

Thanks :) 
Wolfgang

**Comment by PavelLaptev** [comment]
Unfortunately, no. Plugin can't do anything with the user files in the background. System restriction

**Comment by wolfgangbartelme** [comment]
That's what I suspected. Thanks for your quick reply.
