### ISSUE TITLE
Images don't load/paint shapes in Figma

### ISSUE THREAD

**Issue by davebowker** [PavelLaptev/JSON-to-Figma#7]
Hey - great plugin. Using it to pull through data. Have all data pulled but the imageUrl to paint the fill of a shape isn't working. Any ideas? Thanks

**Comment by PavelLaptev** [comment]
Hi, @davebowker ! Thanks for your feedback. Right now plugin doesn't support this feature, but I'm planning to add it in the next release.

**Comment by PavelLaptev** [comment]
@davebowker check the latest release https://www.figma.com/community/plugin/789839703871161985/JSON-to-Figma
